blueprint:
  name: RGBSYNCER (Brightness + Color Temp + Color)
  description: >-
    [![Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fraw.githubusercontent.com%2Firzayev%2Firzayev-ha-blueprints%2Frefs%2Fheads%2Fmain%2Fha-blueprint-rgbsyncer.yaml)

    **RGBSYNCER v1.4-lite** 🎨

    This blueprint syncs only the following attributes between multiple entities:
      - Brightness
      - Color temperature
      - Color (hs_color)

    **NOTE**: It does NOT sync:
      - ON/OFF state
      - Fan speeds

    **CHANGELOG:**
      - 1.4-lite: (2025-08-27)
        - Removed ON/OFF and fan speed sync
        - Kept brightness, color_temp, hs_color

  domain: automation
  input:
    linked_entity:
      name: Linked Entities
      description: Entities whose attributes (brightness, color_temp, hs_color) will be synced.
      selector:
        entity:
          multiple: true
    delay_miliseconds:
      name: Delay
      description: Delay between updates to linked entities
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: milliseconds
          mode: box
      default: 200

mode: single
max_exceeded: silent

variables:
  linked_entities: !input linked_entity

trigger:
  - platform: state
    id: set_brightness
    entity_id: !input linked_entity
    attribute: brightness

  - platform: state
    id: set_color_temp
    entity_id: !input linked_entity
    attribute: color_temp

  - platform: state
    id: set_color
    entity_id: !input linked_entity
    attribute: hs_color

condition:
  - condition: template
    value_template: "{{ trigger.to_state.context.id != this.context.id }}"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: set_brightness
        sequence:
          - variables:
              set_light_brightness: "{{ trigger.to_state.attributes.brightness }}"
          - service: light.turn_on
            data:
              entity_id: "{{ linked_entities | reject('eq', trigger.entity_id) | list }}"
              brightness: "{{ set_light_brightness }}"
          - delay:
              milliseconds: !input delay_miliseconds

      - conditions:
          - condition: trigger
            id: set_color_temp
        sequence:
          - variables:
              set_light_color_temp: "{{ trigger.to_state.attributes.color_temp }}"
          - service: light.turn_on
            data:
              entity_id: "{{ linked_entities | reject('eq', trigger.entity_id) | list }}"
              color_temp: "{{ set_light_color_temp }}"
          - delay:
              milliseconds: !input delay_miliseconds

      - conditions:
          - condition: trigger
            id: set_color
        sequence:
          - variables:
              set_light_color: "{{ trigger.to_state.attributes.hs_color }}"
          - service: light.turn_on
            data:
              entity_id: "{{ linked_entities | reject('eq', trigger.entity_id) | list }}"
              hs_color: "{{ set_light_color }}"
          - delay:
              milliseconds: !input delay_miliseconds
